### ISSUE TITLE
SSH Tunnel with remote host

### ISSUE THREAD

**Issue by rodionchev** [garrylachman/ElectroCRUD#102]
**Describe the bug**
when I try to connect to a database, on a server, on a local network, I get errors:
```
Connection Success
{
	server: {
		valid: false,
		error: 'Error: connect ECONNREFUSED 192.168.1.2:7999'
	},
	ssh: {
		valid: false,
		error: 'Error: read ECONNRESET'
	}
}
```
A connection with similar settings works in Navicat MariaDB.

**To Reproduce**
On server:
1. Install Ubuntu Server 22.04
2. Install ssh server
3. add your user to ssh group
4. install docker 
5. startup docker-container with MariaDB, with option -p 172.17.0.1:7999:3306
6. create database named "test"
7. create user "test" with password "test" and full access to database "test"

On client, in "ElectroCRUD" application:
1. add new connection
9. set account name - "Test"
10. set database server - MySQL
11. press "Next" button
12. in next step (SSH Tunnel):  enable "Configure SSH Tunnel" checkbox
14. hostname - input ip address of server, in local network (192.168.1.2)
15. port - set port 22 (I use the default ssh port)
16. username & password - your username & password, on server
17. in next step (Database): set hostname - ip address of DB server in docker-network (172.17.0.1)
18. set port - 7999
19. set username - test
20. set password - test
21. set database - test

**Expected behavior**
Connection to the test database was expected

**Screenshots**
![Снимок экрана 2022-12-28 в 12 11 01](https://user-images.githubusercontent.com/109942004/209788767-9471f466-0df8-43d7-836b-8195622b54c4.jpg)

![Снимок экрана 2022-12-28 в 12 11 25](https://user-images.githubusercontent.com/109942004/209788823-72f535f3-9f96-4394-94f9-f194412c9238.jpg)

![Снимок экрана 2022-12-28 в 12 11 52](https://user-images.githubusercontent.com/109942004/209788843-a0821a6b-58e4-4b7f-974c-5d7c10056cde.jpg)

![Снимок экрана 2022-12-28 в 12 12 35](https://user-images.githubusercontent.com/109942004/209788982-ab9a2d48-c88d-48a9-bdf7-9f1db38b710c.jpg)

In Navicat (connection test - passed successful)
![Снимок экрана 2022-12-28 в 12 14 16](https://user-images.githubusercontent.com/109942004/209789005-9964eddb-5f33-40a0-b78c-999d89c706d1.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: Monterey 12.3.1

**Console Log**
```
{
	server: {
		valid: false,
		error: 'Error: connect ECONNREFUSED 192.168.1.2:7999'
	},
	ssh: {
		valid: false,
		error: 'Error: read ECONNRESET'
	}
}
UI
{
	server: {
		server_type: '1',
		hostname: '172.17.0.1',
		port: 7999,
		username: 'test',
		password: 'test',
		database: 'test'
	},
	ssh: {
		enabled: true,
		hostname: '192.168.1.2',
		port: '22',
		username: '******',
		password: '******',
		use_key: false,
		key: null
	}
}
UI
Connecting: {"host":"192.168.1.2","port":7999,"user":"test","password":"test","database":"test"}
```

**Comment by lastsamurai26** [comment]
I guess this project is dead

This problem I have reported for a long time but nothing was done 

https://github.com/garrylachman/ElectroCRUD/issues/59

**Comment by garrylachman** [comment]
This but is closed as part of preparing of moving to a new v3.
Its 100% new code in React.

Develop branch:
https://github.com/garrylachman/ElectroCRUD/tree/develop

First preview video:
https://youtube.com/watch?v=gJzlxg2jK9g&feature=share
