### ISSUE TITLE
Error on Edit sigle row

### ISSUE THREAD

**Issue by Razzo1987** [garrylachman/ElectroCRUD#16]
When I edit a single row I have this error:

`
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''DOC_COD', 'cognome', 'nome', 'SSD_DOC', 'web_page', 'mail', 'telefono', 'dipart' at line 1
`

**Comment by Razzo1987** [comment]
This is the table schema:

`
-- phpMyAdmin SQL Dump
-- version 4.0.10.7
-- http://www.phpmyadmin.net
--
-- Host: localhost:3306
-- Generato il: Giu 05, 2016 alle 13:41
-- Versione del server: 5.5.34-32.0-log
-- Versione PHP: 5.4.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Database: `sviluppo_unimib`
--

-- --------------------------------------------------------

--
-- Struttura della tabella `docenti`
--

CREATE TABLE IF NOT EXISTS `docenti` (
  `DOC_COD` varchar(6) NOT NULL,
  `cognome` varchar(40) NOT NULL,
  `nome` varchar(40) NOT NULL,
  `nominativo` varchar(50) NOT NULL,
  `CF_DOC` varchar(16) NOT NULL,
  `SSD_DOC` varchar(13) NOT NULL,
  `web_page` varchar(255) NOT NULL,
  `mail` varchar(255) NOT NULL,
  `telefono` varchar(15) NOT NULL,
  `dipartimento` varchar(30) NOT NULL,
  PRIMARY KEY (`DOC_COD`),
  UNIQUE KEY `CF_DOC` (`CF_DOC`),
  KEY `SSD_DOC` (`SSD_DOC`),
  KEY `dipartimento` (`dipartimento`),
  KEY `dipartimento_2` (`dipartimento`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dump dei dati per la tabella `docenti`
--

INSERT INTO `docenti` (`DOC_COD`, `cognome`, `nome`, `nominativo`, `CF_DOC`, `SSD_DOC`, `web_page`, `mail`, `telefono`, `dipartimento`) VALUES
('000100', 'ROSSI', 'MARIO', 'ROSSI Mario', 'XXXXX1', 'INF/01', 'http://www.test.it/a', 'mario.rossi@test.it', '02 1234 5678', 'A'),
('000102', 'VERDI', 'PAOLO', 'VERDI Paolo', 'XXXXX2', 'IUS/17', 'http://www.test.it/b', 'paolo.verdi@test.it', '02 1234 5679', 'B'),
('000106', 'BIANCHI', 'LUCA', 'BIANCHI Luca', 'XXXXX3', 'SECS-P/01', '', '', '', 'C');

--
-- Limiti per le tabelle scaricate
--

--
-- Limiti per la tabella `docenti`
--
ALTER TABLE `docenti`
  ADD CONSTRAINT `docenti_ibfk_1` FOREIGN KEY (`SSD_DOC`) REFERENCES `SSD` (`SSD`),
  ADD CONSTRAINT `docenti_ibfk_2` FOREIGN KEY (`dipartimento`) REFERENCES `dipartimenti` (`DIP_COD`);
`

**Comment by garrylachman** [comment]
1. Its working for me (i create the same table)
2. Check if you are using version 0.8.3, its looks like bug i fix in latest version

**Comment by Razzo1987** [comment]
Yes on the v 0.8.4 it is solved!
