### ISSUE TITLE
Error npm install

### ISSUE THREAD

**Issue by helloitu** [garrylachman/ElectroCRUD#18]
npm ERR! not a package /tmp/npm-8331-N1ca2H2B/github.com/garrylachman/github-update-checker.git
npm ERR! Error: ENOENT: no such file or directory, open '/tmp/npm-8331-N1ca2H2B/github.com/garrylachman/github-update-checker.git-unpack/package.json'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/CRUDs/ElectronCRUD/ElectroCRUD
npm ERR! node -v v4.4.3
npm ERR! npm -v 1.4.21
npm ERR! path /tmp/npm-8331-N1ca2H2B/github.com/garrylachman/github-update-checker.git-unpack/package.json
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! not a package /tmp/npm-8331-N1ca2H2B/github.com/SoftwearDevelopment/grunt-contrib-uglify.git
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/CRUDs/ElectronCRUD/ElectroCRUD/npm-debug.log
npm ERR! not ok code 0

**Comment by john24318** [comment]
Modify grunt-contrib-uglify and github-update-checker to the correct versions in the package.json
