### ISSUE TITLE
socketPath in MAMP connection

### ISSUE THREAD

**Issue by 7ender** [garrylachman/ElectroCRUD#24]
In macOS with MAMP need add field for socketPath on page "Project details". 

example:
`this.socketPath         = options.socketPath || '/Applications/MAMP/tmp/mysql/mysql.sock';`

Otherwise: "Error: connect ECONNREFUSED 127.0.0.1:3306"

**Comment by erolando** [comment]
same problema

**Comment by mittalapurv** [comment]
How do we add the socketPath?? Where to add it? I apologize in advance, but please treat me as a noob
