### ISSUE TITLE
Edit (Update all records)

### ISSUE THREAD

**Issue by picepice** [garrylachman/ElectroCRUD#25]
When i edit and save. All the records are affected and changed.

**Comment by flazx** [comment]
I think you have to comment below code in the data-helper.js, delete data[schemaBuilder.getPrimaryKey()];
that lead to affect all the code.

**Comment by flazx** [comment]
I think you have to comment below code in the data-helper.js, 

> delete data[schemaBuilder.getPrimaryKey()];

that lead to affect all the code.

**Comment by vynnus** [comment]
same issue here.
seems the project was abandonned
