### ISSUE TITLE
mysql database connexion issue when starting a new project

### ISSUE THREAD

**Issue by lcoulon** [garrylachman/ElectroCRUD#29]
Hello

I download ElectoCRUD-win32-x64 archive, extracted into a folder and ran ElectoCRUD.exe

From here, i try to built my first project but mysql database can't be reach although i'm sure the credentials have been properly entered.

Did i miss something ?

![capture](https://user-images.githubusercontent.com/6061092/28104745-e25e09ca-66dc-11e7-81f1-359ccbc161c5.png)

**Comment by nicolasguzca** [comment]
The error says your host cannot be found. Have you tried doing a ping from your machine to the host?
Does your MySQL username have the permissions to connect remotely?
