### ISSUE TITLE
can't see MYSQL DB tables 

### ISSUE THREAD

**Issue by moda20** [garrylachman/ElectroCRUD#39]
![Screen Shot 2019-07-13 at 20 03 04](https://user-images.githubusercontent.com/23613485/61175535-4eb43600-a5a9-11e9-81f4-432e9efdf1b1.png)

I can't see the tables after choosing my db, I also connect successfully to the DB

**Comment by garrylachman** [comment]
can you provide more info like
OS, MySQL Version, Engines

**Comment by moda20** [comment]
MacOs Mojave 10.14.1
8.0.15 MySQL Community Server - GPL
Engines ? what is that ?

**Comment by garrylachman** [comment]
I'm almost on the same setup.
Close the app & open it again and write me step by step what are you doing.
