### ISSUE TITLE
not support MySQL 8

### ISSUE THREAD

**Issue by iminto** [garrylachman/ElectroCRUD#41]
MySQL version: 8.0.15

when i click "START TEST",error occurs:
```
resMessage { server:
   { valid: false,
     error:
      'Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client' },
  ssh: { valid: undefined, error: undefined } }

```

**Comment by garrylachman** [comment]
I test it on 10.4.6-MariaDB, will test it with MySQL 8.0.15.
Thanks

**Comment by garrylachman** [comment]
Ok,
MySQL 8 Support depends on the merging of https://github.com/mysqljs/mysql/pull/2233 pull.
Right now, node MySQL lib doesn't support the new MySQL 8 Auth.
