### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by fthamura** [garrylachman/ElectroCRUD#5]
npm start like this.. how to make it run like demo?

![screenshot from 2016-05-20 20-02-48](https://cloud.githubusercontent.com/assets/218106/15428499/e81d65aa-1ec5-11e6-8096-eacd667d4377.png)

**Comment by garrylachman** [comment]
its working for me, im on osx... try to debug it..

**Comment by garrylachman** [comment]
Did you install all bower & npm dependencies?
