### ISSUE TITLE
Password for private key for ssl tunnel

### ISSUE THREAD

**Issue by pomazanbohdan** [garrylachman/ElectroCRUD#52]
Need field to password

![image](https://user-images.githubusercontent.com/696713/62999656-c6f76b00-be77-11e9-8154-f27f65423814.png)

**Comment by garrylachman** [comment]
This bug is closed as part of preparing of moving to a new v3.
Its 100% new code in React.

Develop branch:
https://github.com/garrylachman/ElectroCRUD/tree/develop

First preview video:
https://youtube.com/watch?v=gJzlxg2jK9g&feature=share
