### ISSUE TITLE
SSH tunnel with database localhost

### ISSUE THREAD

**Issue by lastsamurai26** [garrylachman/ElectroCRUD#59]
**Describe the bug**
I have configured an SSH tunnel with a PPK file. The tunnel is being built but the database connection is not working.
I have a MariaDB 10.3 running on the remote server.
Settings: 
SSH domain.de port 2212  username sshkey
mysql localhost 3306 username password databasename

**To Reproduce**
I don't know how to comprehend this. 
But in the screen you can see quite well that he wants to establish a database connection with port 5000 but I have definitely specified port 3306. 

**Screenshots**
<img width="650" alt="Bildschirmfoto 2019-10-24 um 19 51 25" src="https://user-images.githubusercontent.com/3257844/67512140-76cb2f00-f698-11e9-946e-fef574ba5f61.png">

**Desktop (please complete the following information):**
 - OS: MacOS X catalina, WIndows 10 
 - Version MacOS 10.15, Windows 10 1903

**Additional context**
It's the program I've been searching for years for my databases.

**Comment by garrylachman** [comment]
Port 5000 is the Tunnel port, the connection to port 5000 must be tunneled to 3306.
It looks like MySQL user permissions issue.  try to add the same user with '%' as host like:

`CREATE USER 'myuser'@'%' IDENTIFIED BY 'password';`

`GRANT ALL PRIVILEGES ON * . * TO 'myuser'@'%';`

`FLUSH PRIVILEGES;`

**Comment by lastsamurai26** [comment]
Unfortunately, this does not solve the problem either. I only bound my mysqlserver to 127.0.0.1 and localhost. Do I have to let the SQL Server listen to my own IP?

**Comment by lastsamurai26** [comment]
How do I configure my mysql server to work with this tool?
I assumed that the tool would establish an SSH connection and then execute the command locally on the remote server as mysql, as if you were connecting via putty and using mysql.

**Comment by edo-2313** [comment]
bump this, I have the same problem. My db is only accessible from localhost and I'd like to ssh tunnel into it. Any ideas?

**Comment by lastsamurai26** [comment]
not really 

For the connection to work for me I have to open the user and the server to the world

**Comment by garrylachman** [comment]
This bug is closed as part of preparing of moving to a new v3.
Its 100% new code in React.

Develop branch:
https://github.com/garrylachman/ElectroCRUD/tree/develop

First preview video:
https://youtube.com/watch?v=gJzlxg2jK9g&feature=share
