### ISSUE TITLE
Allow user to add table from interface itself also allow to map relation between two tables .

### ISSUE THREAD

**Issue by bunny-poooh** [garrylachman/ElectroCRUD#67]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by garrylachman** [comment]
1. There is option to create a relation between 2 tables  and even between columns (join)
Both of the tables must be added as views, then edit the view and create the relation.

2. Creating new tables in DB from the CRUD is out of scope right now...

**Comment by bunny-poooh** [comment]
garrylachman Thanks
