### ISSUE TITLE
npm install command gives this error 

### ISSUE THREAD

**Issue by blackcod3r** [garrylachman/ElectroCRUD#68]
PS X:\angular\ElectroCRUD> npm install
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @types/handlebars@4.1.0: This is a stub types definition. handlebars provides its own type definitions, so you do not need this installed.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.     
npm WARN deprecated webdriverio@4.14.4: outdated version, please use @next

> electron-chromedriver@7.0.0 install X:\angular\ElectroCRUD\node_modules\electron-chromedriver
> node ./download-chromedriver.js

> core-js@3.2.1 postinstall X:\angular\ElectroCRUD\node_modules\@angular-devkit\build-angular\node_modules\core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> core-js@2.6.11 postinstall X:\angular\ElectroCRUD\node_modules\babel-runtime\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> ejs@2.7.4 postinstall X:\angular\ElectroCRUD\node_modules\ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

> core-js@3.6.4 postinstall X:\angular\ElectroCRUD\node_modules\global-agent\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.11 postinstall X:\angular\ElectroCRUD\node_modules\wait-on\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> @angular/cli@8.3.20 postinstall X:\angular\ElectroCRUD\node_modules\@angular\cli
> node ./bin/postinstall/script.js

> core-js@3.4.7 postinstall X:\angular\ElectroCRUD\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> electron@7.1.12 postinstall X:\angular\ElectroCRUD\node_modules\electron
> node install.js

> ElectroCRUD@2.5.3 postinstall X:\angular\ElectroCRUD
> npm run postinstall:electron && ./node_modules/electron-builder/out/cli/cli.js install-app-deps

> ElectroCRUD@2.5.3 postinstall:electron X:\angular\ElectroCRUD
> node postinstall

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ElectroCRUD@2.5.3 postinstall: `npm run postinstall:electron && ./node_modules/electron-builder/out/cli/cli.js install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ElectroCRUD@2.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\I.T\AppData\Roaming\npm-cache\_logs\2020-02-20T05_57_18_042Z-debug.log
PS X:\angular\ElectroCRUD> 

Seems the issues happens at this command

> ElectroCRUD@2.5.3 postinstall X:\angular\ElectroCRUD
> npm run postinstall:electron && ./node_modules/electron-builder/out/cli/cli.js install-app-deps

Please forgive me if i'm doing this wrong, I don't mean to be rude or anything, it is just that i am new to all of this and this is my first time here. I've been trying to install Electro Crud for a week now and doing research to find my way around it. but I always end up with this error.

My details are as follows 

PS X:\angular\ElectroCRUD> npm -v
6.13.4

PS X:\angular\ElectroCRUD> node -v
v12.16.0

PS X:\angular\ElectroCRUD> ng -version 
Your global Angular CLI version (9.0.2) is greater than your local
version (8.3.20). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

Thank You

**Comment by garrylachman** [comment]
1. you can download the binaries - you need to compile it only in case you want to modify the code.
2. can you send the content of the complete log. "C:\Users\I.T\AppData\Roaming\npm-cache_logs\2020-02-20T05_57_18_042Z-debug.log"

**Comment by blackcod3r** [comment]
But my depoyment is on windows platform? The windows binary is exe extension, How do I go about it? Im sorry but im really REALLY new at this. I dont mean to be bother.

**Comment by garrylachman** [comment]
https://github.com/garrylachman/ElectroCRUD/releases/download/2.6.0/ElectroCRUD.2.6.0.exe

This is windows binary
