### ISSUE TITLE
Rename fields

### ISSUE THREAD

**Issue by eladeyal-intel** [garrylachman/ElectroCRUD#69]
(It's so great to see this app live again!!)

It should be possible to "rename" the display value of  field. i.e., My table has a field (column) "genretype" it should be presented as "Genre Type". Following the great examples from [Metabase](https://github.com/metabase/metabase) you can start with a sane guesstimate (i.e., if the field name is CamelCase then you can convert it to words) and also let operator edit this mapping.

**Comment by garrylachman** [comment]
This bug is closed as part of preparing of moving to a new v3.
Its 100% new code in React.

Develop branch:
https://github.com/garrylachman/ElectroCRUD/tree/develop

First preview video:
https://youtube.com/watch?v=gJzlxg2jK9g&feature=share
