### ISSUE TITLE
Filter should support string operators

### ISSUE THREAD

**Issue by eladeyal-intel** [garrylachman/ElectroCRUD#70]
It seems that trying to define a filter only supports `>` `=` `<` operators.

For VARCHAR (and text entries) - you'd want other operators. At least: `Contains` and `Does not contain`

![image](https://user-images.githubusercontent.com/20379005/75094897-037af080-5598-11ea-96b3-6a6cc10db8c6.png)

**Comment by garrylachman** [comment]
I think LIKE operator will conver this.
wil add this for plan for future version

**Comment by eladeyal-intel** [comment]
Like and not like will be great

**Comment by garrylachman** [comment]
done... v.2.6.0

**Comment by eladeyal-intel** [comment]
I propose you also want 'not like' operator
