### ISSUE TITLE
Admin vs User views

### ISSUE THREAD

**Issue by eladeyal-intel** [garrylachman/ElectroCRUD#71]
It would be super useful if there was a way to "log-in" into the app in two ways: "User" and "Admin". Where "Admin" can edit which views from the database are presented, and which can be operations are allowed; and the "user" has only these capabilities presented to him/her.

**Comment by garrylachman** [comment]
As a workaround you can create a read-only user in your database and use this user as User.

I will add this as plan feature.

**Comment by eladeyal-intel** [comment]
I was not clear. I want user to be able to CRUD only those tables and operations that the admin allowed, but not able to add new views or edit views for example.

**Comment by garrylachman** [comment]
This bug is closed as part of preparing of moving to a new v3.
Its 100% new code in React.

Develop branch:
https://github.com/garrylachman/ElectroCRUD/tree/develop

First preview video:
https://youtube.com/watch?v=gJzlxg2jK9g&feature=share
