### ISSUE TITLE
App threw an error during load

### ISSUE THREAD

**Issue by tahirsohaib** [garrylachman/ElectroCRUD#75]
Unable to run the app. Heres the issue: 

<img width="715" alt="Screenshot 2020-05-23 at 5 33 48 am" src="https://user-images.githubusercontent.com/9818409/82717647-fb297300-9cb6-11ea-9ba6-d283ac61f5b1.png">

**Comment by garrylachman** [comment]
how do you run it? can you send me reproduce steps

**Comment by garrylachman** [comment]
This bug is closed as part of preparing of moving to a new v3.
Its 100% new code in React.

Develop branch:
https://github.com/garrylachman/ElectroCRUD/tree/develop

First preview video:
https://youtube.com/watch?v=gJzlxg2jK9g&feature=share
