### ISSUE TITLE
BLOB is a text field for insertion

### ISSUE THREAD

**Issue by AbdulRafay** [garrylachman/ElectroCRUD#76]
Hi,

First of all, thanks for building such great app. While using it I noticed that BLOB field is a textarea, if it can be replaced with file picker that would be great, did I miss any configuration or its not supported yet? Please refer to screenshot below:
![image](https://user-images.githubusercontent.com/614883/85473722-172d7680-b5cd-11ea-97ee-560d5624d9bc.png)

Thanks

**Comment by garrylachman** [comment]
Thanks, i will add this to the roadmap

**Comment by garrylachman** [comment]
This bug is closed as part of preparing of moving to a new v3.
Its 100% new code in React.

Develop branch:
https://github.com/garrylachman/ElectroCRUD/tree/develop

First preview video:
https://youtube.com/watch?v=gJzlxg2jK9g&feature=share
