### ISSUE TITLE
Flatpak release

### ISSUE THREAD

**Issue by ptman** [garrylachman/ElectroCRUD#80]
Please consider flatpak release for cross-distribution linux packaging. Snap is basically ubuntu only. AppImage doesn't have automatic updating.

**Comment by garrylachman** [comment]
This bug is closed as part of preparing of moving to a new v3.
Its 100% new code in React.

Develop branch:
https://github.com/garrylachman/ElectroCRUD/tree/develop

First preview video:
https://youtube.com/watch?v=gJzlxg2jK9g&feature=share
