### ISSUE TITLE
Unable to Add new connection with Docker & WSL 2 on Windows 10

### ISSUE THREAD

**Issue by gethari** [garrylachman/ElectroCRUD#81]
**Describe the bug**
I have a docker container which is running `postgres` & `pgadmin` via WSL on Windows machine. I am able to connect to the database using `localhost:5050`. Please refer the attached screenshots.

**To Reproduce**
1. Installed ElectroCRUD
2. Added necessary details
3. I am unable to click on `SAVE` button

**Expected behavior**
Should be able to add new connection.

**Screenshots**

![image](https://user-images.githubusercontent.com/20477956/89425255-67643080-d756-11ea-92ba-738251f442db.png)

![image](https://user-images.githubusercontent.com/20477956/89425457-a72b1800-d756-11ea-97ae-eb17152bc6f4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 2004 19041.329 & running WSL 2
 - Version : Latest Electro CRUD

**Additional context**

Also tried to toggle the developer tools from the application to see if there are any errors, but i cannot find any

**Comment by garrylachman** [comment]
its looks like port 80 is mapped to port 5050....

**Comment by garrylachman** [comment]
the bug fixed... will release new version soon

**Comment by garrylachman** [comment]
released ver 2.7.1
