### ISSUE TITLE
Cockroachdb Support

### ISSUE THREAD

**Issue by fire** [garrylachman/ElectroCRUD#83]
**Is your feature request related to a problem? Please describe.**
I have a cockroachdb cluster, I want to use it.

**Describe the solution you'd like**
Have cockroachdb support. Use the existing postgresql support.

**Describe alternatives you've considered**
Use the postgresql support as is.

**Additional context**
Plan:

* Copy the postgresql support.

**Comment by garrylachman** [comment]
This bug is closed as part of preparing of moving to a new v3.
Its 100% new code in React.

Develop branch:
https://github.com/garrylachman/ElectroCRUD/tree/develop

First preview video:
https://youtube.com/watch?v=gJzlxg2jK9g&feature=share
