### ISSUE TITLE
Can't connect to an heroku prod pg instance

### ISSUE THREAD

**Issue by rsylvian** [garrylachman/ElectroCRUD#84]
Hi there! Having issues connecting to a Postgres heroku production database:

<img width="670" alt="Screen Shot 2020-08-19 at 4 19 38 AM" src="https://user-images.githubusercontent.com/1449325/90629108-9dcc9180-e1d3-11ea-9fe2-c63979369584.png">

From heroku:

> The authentication failed because the connection didn't use SSL encryption: (SSL off). All Heroku Postgres production databases require using SSL connections to ensure that communications between applications and the database remain secure. If your client is not using SSL to connect to your database, you would see these errors even if you're using the right credentials to connect to it.

source: https://help.heroku.com/DR0TTWWD/seeing-fatal-no-pg_hba-conf-entry-errors-in-postgres

**Desktop:**
 - OS: OS X 10.15.6
 - Version: 2.7.1

**Comment by garrylachman** [comment]
This bug is closed as part of preparing of moving to a new v3.
Its 100% new code in React.

Develop branch:
https://github.com/garrylachman/ElectroCRUD/tree/develop

First preview video:
https://youtube.com/watch?v=gJzlxg2jK9g&feature=share
