### ISSUE TITLE
Malware in ElectroCRUD 2 ?

### ISSUE THREAD

**Issue by accnetdev** [garrylachman/ElectroCRUD#85]
Impossible to install ElectroCRUD 2, my Kaspersky remove it as it detects a malware like 2 other antimalwares.

[https://www.virustotal.com/gui/file/235a9023ed9f08d8076feb4e1037df59aaf119ea6ba29a98ece2144cbfb6c334/detection]

Kaspersky = Trojan.Win32.Redyms.vkg

Yandex = Riskware.Agent!

ZoneAlarm by Check Point = Trojan.Win32.Redyms.vkg

**Comment by garrylachman** [comment]
remove the installer and upload portable verszion... now its ok

**Comment by accnetdev** [comment]
Thanks, no longer Kaspersky warning/removal.
If you used an external installer, It could be useful to get information on it.

**Comment by garrylachman** [comment]
Some guy help me with that, I need to check better next time. He used advanced installer, maybe it's was cracked version.  ---- On Mon, 24 Aug 2020 11:03:02 +0300  notifications@github.com  wrote ----
Thanks, no longer Kaspersky warning/removal.
If you used an external installer, It could be useful to get information on it.

**Comment by accnetdev** [comment]
OK thanks again for your help.

**Comment by accnetdev** [comment]
FYI your site : http://www.garry-lachman.com/ is redirected to https://52nhsur4.vip/?channelCode=XURZ2

**Comment by garrylachman** [comment]
Not renew the domain for years ---- On Mon, 24 Aug 2020 11:56:40 +0300  notifications@github.com  wrote ----
FYI your site : http://www.garry-lachman.com/ is redirected to https://52nhsur4.vip/?channelCode=XURZ2
