### ISSUE TITLE
TLS postgresql connect

### ISSUE THREAD

**Issue by jbrindle** [garrylachman/ElectroCRUD#89]
**Is your feature request related to a problem? Please describe.**
I cannot connect to our databases because they use sslmode=verify-full

**Describe the solution you'd like**
Support setting key, cert, and ca for connections. 

**Describe alternatives you've considered**
None, need sslmode to connect.

**Comment by garrylachman** [comment]
This bug is closed as part of preparing of moving to a new v3.
Its 100% new code in React.

Develop branch:
https://github.com/garrylachman/ElectroCRUD/tree/develop

First preview video:
https://youtube.com/watch?v=gJzlxg2jK9g&feature=share
