### ISSUE TITLE
Unable to edit (update) field in view (table)

### ISSUE THREAD

**Issue by jayurbain** [garrylachman/ElectroCRUD#96]
**Describe the bug**
Unable to edit columns in a row.

**To Reproduce**
1. Create a view using "+ Add View" to query a database table
2. Click on the 3 vertical dots on the right side of a row
3. Select edit
4. Nothing happens

Notes: 
- Using the '+' at the top of the view display grid I'm able to add a new row.
- I added and ran a "Custom Query". Could edit the "spreadsheet" view but it did not persiste.

**Expected behavior**
I would like to edit the columns for a selected row.

**Screenshots**
![image](https://user-images.githubusercontent.com/3729362/107078473-fe687e80-67b3-11eb-967c-575c22b7264e.png)

**Desktop (please complete the following information):**
 - OS X
 - 10.13.6
 - MySQL 8.0.12

**Additional context**
Thanks for your efforts with this tool.

Any help would be appreciated. Need tool like this for non-SQL users. Thanks, Jay

**Comment by MrMr90** [comment]
I'm having the same problem. Clicking the edit button does nothing. This is an awesome tool and we could use this in my org, and I'm assuming there must be a fix for this! Thanks so much for all your hard work - this is revolutionary.

Windows 10, MySQL MariaDB 10.4.14, ElectroCrud Version 10.0.0.

![image](https://user-images.githubusercontent.com/25942575/111254777-f67dd480-85d2-11eb-84ea-eff5c57d929b.png)

**Comment by kakarottobcn** [comment]
Hi, same problem here. When clicking the Edit button, simply nothing happens. No new window to edit, nothing. This is an awesome tool, I hope you fix this bug because I'm really going to use electroCRUD. I'm using version 2.8.0.

**Comment by garrylachman** [comment]
This bug is closed as part of preparing of moving to a new v3.
Its 100% new code in React.

Develop branch:
https://github.com/garrylachman/ElectroCRUD/tree/develop

First preview video:
https://youtube.com/watch?v=gJzlxg2jK9g&feature=share
