### ISSUE TITLE
Install in Ubuntu 20.4

### ISSUE THREAD

**Issue by Jpsanchezasmalljob** [garrylachman/ElectroCRUD#97]
Hello, 

In order to install it in UBUNTU 20.4  it will be great if you have any more detail instructions about it. 

As per General instructions, unfortunately i can´t successful install it. 

Thanks in advance!
JP

**Comment by karawitan** [comment]
Hi !
 once you've downloaded the .AppImage file, as mentioned in README.md at "Download Binaries", you have to:
- open a terminal
- type (skip the lines beginning with #, these are comments):

```
# Make the program executable, using chmod
 chmod +x ./ElectroCRUD-2.8.0.AppImage 

# Execute it
./ElectroCRUD-2.8.0.AppImage 
```

These instructions are very basic knowledge for the Linux user, that's probably why they are not mentioned in the README.md

The same operations may be done also using graphical mode, but there are so many options out there that it's difficult to describe. This is also basic Linux knowledge.

Hope this helps,

Sincerelly

**Comment by karawitan** [comment]
BTW, there is some documentation about ElectrCRUD AppImage [here](https://appimage.github.io/ElectroCRUD)

**Comment by vitormicillo** [comment]
I think what @Jpsanchezasmalljob meant is if it would be possible to step by step with more details to install on your local linux if you want to compile the application from source after cloning the repository.
Because simply cloning the files locally and running an "npm install" doesn't work.

**Comment by garrylachman** [comment]
This bug is closed as part of preparing of moving to a new v3.
Its 100% new code in React.

Develop branch:
https://github.com/garrylachman/ElectroCRUD/tree/develop

First preview video:
https://youtube.com/watch?v=gJzlxg2jK9g&feature=share
