### ISSUE TITLE
Will not build or run on Windows

### ISSUE THREAD

**Issue by nomadtechiemike** [garrylachman/ElectroCRUD#98]
**Describe the bug**
WARNING in E:\GitHub\ElectroCRUD\src\backend\index.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in E:\GitHub\ElectroCRUD\main.ts is part of the TypeScript compilation but it's unused.  
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in E:\GitHub\ElectroCRUD\src\polyfills-test.ts is part of the TypeScript compilation but 
it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in E:\GitHub\ElectroCRUD\src\test.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in E:\GitHub\ElectroCRUD\src\environments\environment.dev.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in E:\GitHub\ElectroCRUD\src\environments\environment.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in E:\GitHub\ElectroCRUD\src\shared\interfaces\extension.interface.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ElectroCRUD@2.8.0 electron:mac-win-linux: `npm run build:prod && ./node_modules/electron-builder/out/cli/cli.js build --mac --win --linux`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ElectroCRUD@2.8.0 electron:mac-win-linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Fails to run on windows 10

**Comment by conFusl** [comment]
+1 same error on my side.

**Comment by garrylachman** [comment]
This bug is closed as part of preparing of moving to a new v3.
Its 100% new code in React.

Develop branch:
https://github.com/garrylachman/ElectroCRUD/tree/develop

First preview video:
https://youtube.com/watch?v=gJzlxg2jK9g&feature=share
